ServerEvents.recipes(event => {
    event.remove({ id: 'createthrusters:alternator' })
    event.remove({ id: 'createthrusters:analogue_contraption_controller' })
    event.remove({ id: 'createthrusters:andesite_cable' })
    event.remove({ id: 'createthrusters:bidirectional_gearbox' })
    event.remove({ id: 'createthrusters:contraption_network_linker' })
    event.remove({ id: 'createthrusters:gyroscope_link' })
    event.remove({ id: 'createthrusters:industrial_motor' })
    event.remove({ id: 'createthrusters:physics_goggles' })
    event.remove({ id: 'createthrusters:physics_staff' })
    event.remove({ id: 'createthrusters:processing_upgrade_haunting_t1' })
    event.remove({ id: 'createthrusters:processing_upgrade_haunting_t2' })
    event.remove({ id: 'createthrusters:processing_upgrade_haunting_t3' })
    event.remove({ id: 'createthrusters:processing_upgrade_haunting_t4' })
    event.remove({ id: 'createthrusters:processing_upgrade_smelting_t1' })
    event.remove({ id: 'createthrusters:processing_upgrade_smelting_t2' })
    event.remove({ id: 'createthrusters:processing_upgrade_smelting_t3' })
    event.remove({ id: 'createthrusters:processing_upgrade_smelting_t4' })
    event.remove({ id: 'createthrusters:processing_upgrade_smoking_t1' })
    event.remove({ id: 'createthrusters:processing_upgrade_smoking_t2' })
    event.remove({ id: 'createthrusters:processing_upgrade_smoking_t3' })
    event.remove({ id: 'createthrusters:processing_upgrade_smoking_t4' })
    event.remove({ id: 'createthrusters:propulsion_upgrade_t1' })
    event.remove({ id: 'createthrusters:propulsion_upgrade_t2' })
    event.remove({ id: 'createthrusters:propulsion_upgrade_t3' })
    event.remove({ id: 'createthrusters:propulsion_upgrade_t4' })
    event.remove({ id: 'createthrusters:rope_knot' })
    event.remove({ id: 'createthrusters:thruster' })
    event.remove({ id: 'createthrusters:thruster_lense' })
    event.remove({ id: 'createthrusters:variable_transmission' })
    event.remove({ id: 'createthrusters:vertical_bidirectional_gearbox' })
    event.remove({ id: 'createthrusters:vertical_variable_transmission' })
})

RecipeViewerEvents.removeEntries('item', event => {
    event.remove('createthrusters:alternator')
    event.remove('createthrusters:analogue_contraption_controller')
    event.remove('createthrusters:andesite_cable')
    event.remove('createthrusters:bidirectional_gearbox')
    event.remove('createthrusters:contraption_network_linker')
    event.remove('createthrusters:gyroscope_link')
    event.remove('createthrusters:industrial_motor')
    event.remove('createthrusters:physics_goggles')
    event.remove('createthrusters:physics_staff')
    event.remove('createthrusters:processing_upgrade_haunting_t1')
    event.remove('createthrusters:processing_upgrade_haunting_t2')
    event.remove('createthrusters:processing_upgrade_haunting_t3')
    event.remove('createthrusters:processing_upgrade_haunting_t4')
    event.remove('createthrusters:processing_upgrade_smelting_t1')
    event.remove('createthrusters:processing_upgrade_smelting_t2')
    event.remove('createthrusters:processing_upgrade_smelting_t3')
    event.remove('createthrusters:processing_upgrade_smelting_t4')
    event.remove('createthrusters:processing_upgrade_smoking_t1')
    event.remove('createthrusters:processing_upgrade_smoking_t2')
    event.remove('createthrusters:processing_upgrade_smoking_t3')
    event.remove('createthrusters:processing_upgrade_smoking_t4')
    event.remove('createthrusters:propulsion_upgrade_t1')
    event.remove('createthrusters:propulsion_upgrade_t2')
    event.remove('createthrusters:propulsion_upgrade_t3')
    event.remove('createthrusters:propulsion_upgrade_t4')
    event.remove('createthrusters:rope_knot')
    event.remove('createthrusters:thruster')
    event.remove('createthrusters:thruster_lense')
    event.remove('createthrusters:variable_transmission')
    event.remove('createthrusters:vertical_bidirectional_gearbox')
    event.remove('createthrusters:vertical_variable_transmission')
})